/** @type {import('tailwindcss').Config} */
export default {
  content: ["./app/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#555e74",
        "on-primary": "#273044",
        "on-tertiary-container": "#ad7f39",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed": "#d9e2fc",
        "on-secondary-container": "#acb8d8",
        "on-tertiary-fixed": "#291800",
        "inverse-surface": "#e4e2e4",
        "on-surface-variant": "#c5c6cd",
        "surface-bright": "#39393b",
        background: "#131315",
        "outline-variant": "#45474c",
        "on-primary-container": "#7e889f",
        "on-primary-fixed-variant": "#3d475c",
        "on-secondary": "#243049",
        tertiary: "#f2bd71",
        "on-secondary-fixed": "#0e1b33",
        "primary-container": "#162033",
        "on-secondary-fixed-variant": "#3b4761",
        "error-container": "#93000a",
        "surface-container": "#1f1f21",
        "surface-container-high": "#2a2a2b",
        "on-background": "#e4e2e4",
        "on-surface": "#e4e2e4",
        error: "#ffb4ab",
        "secondary-container": "#3d4964",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-fixed-variant": "#624000",
        "surface-container-low": "#1b1b1d",
        "tertiary-fixed-dim": "#f2bd71",
        "surface-tint": "#bdc6e0",
        "surface-container-highest": "#353436",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#442b00",
        "on-error": "#690005",
        "inverse-on-surface": "#303032",
        "primary-fixed-dim": "#bdc6e0",
        "surface-variant": "#353436",
        "tertiary-fixed": "#ffddb1",
        secondary: "#bac6e6",
        "secondary-fixed-dim": "#bac6e6",
        "surface-dim": "#131315",
        primary: "#bdc6e0",
        "on-primary-fixed": "#111b2e",
        surface: "#131315",
        "tertiary-container": "#2f1c00",
        outline: "#8f9097",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        unit: "8px",
        gutter: "24px",
        "container-max": "1440px",
      },
      maxWidth: {
        container: "1440px",
      },
      fontFamily: {
        "body-md": ["Manrope", "system-ui", "sans-serif"],
        "label-sm": ["Manrope", "system-ui", "sans-serif"],
        "label-md": ["Manrope", "system-ui", "sans-serif"],
        "body-lg": ["Manrope", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "headline-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
};
